image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

build:
  stage: build
  script:
    - cd hackmd
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

